baseURL = "https://zycr.zj991212.workers.dev/"
languageCode = "zh-cn"
title = "ZYCR"

enableRobotsTXT = true

[params]
description = "Personal research, engineering and knowledge archive."

[taxonomies]
tag = "tags"

[markup]

  [markup.goldmark]

    [markup.goldmark.extensions]

      [markup.goldmark.extensions.passthrough]
      enable = true

        [markup.goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)']]

  [markup.highlight]
  lineNos = false
